
export const SET_NER_FILE = 'SET_NER_FILE';
export const ADD_NER_NAME = 'ADD_NER_NAME';
export const TOGGLE_SUBSTITION = 'TOGGLE_SUBSTITION';
export const CHANGE_SUBSTITION = 'CHANGE_SUBSTITION';
export const CHANGE_NER_RETURN_TYPE = 'CHANGE_NER_RETURN_TYPE';
export const CHANGE_NER_TOGGLE_SEARCH_PERSONID = 'CHANGE_NER_TOGGLE_SEARCH_PERSONID';

export const SET_SUMMARY_FILES = 'SET_SUMMARY_FILES';
export const SET_SUMMARY_METHOD = 'SET_SUMMARY_METHOD';
export const SET_SUMMARY_LENGTH = 'SET_SUMMARY_LENGTH';
export const CHANGE_SUMMARY_RETURN_TYPE = 'CHANGE_SUMMARY_RETURN_TYPE';
