
export const SET_NER_FILE = 'SET_NER_FILE';
export const ADD_NER_NAME = 'ADD_NER_NAME';
export const TOGGLE_SUBSTITION = 'TOGGLE_SUBSTITION';
export const CHANGE_SUBSTITION = 'CHANGE_SUBSTITION';
export const CHANGE_NER_RETURN_TYPE = 'CHANGE_NER_RETURN_TYPE';
